export const majorPincodes = [
  // North India
  { pincode: "110001", city: "New Delhi", state: "Delhi" },
  { pincode: "110020", city: "South Delhi", state: "Delhi" },
  { pincode: "201301", city: "Noida", state: "Uttar Pradesh" },
  { pincode: "226001", city: "Lucknow", state: "Uttar Pradesh" },
  { pincode: "208001", city: "Kanpur", state: "Uttar Pradesh" },
  { pincode: "221001", city: "Varanasi", state: "Uttar Pradesh" },
  { pincode: "250001", city: "Meerut", state: "Uttar Pradesh" },
  { pincode: "243001", city: "Bareilly", state: "Uttar Pradesh" },
  { pincode: "302001", city: "Jaipur", state: "Rajasthan" },
  { pincode: "342001", city: "Jodhpur", state: "Rajasthan" },
  { pincode: "313001", city: "Udaipur", state: "Rajasthan" },
  { pincode: "334001", city: "Bikaner", state: "Rajasthan" },
  { pincode: "305001", city: "Ajmer", state: "Rajasthan" },
  { pincode: "160001", city: "Chandigarh", state: "Chandigarh" },
  { pincode: "180001", city: "Jammu", state: "Jammu and Kashmir" },
  { pincode: "190001", city: "Srinagar", state: "Jammu and Kashmir" },
  { pincode: "173212", city: "Shimla", state: "Himachal Pradesh" },
  { pincode: "176001", city: "Kullu", state: "Himachal Pradesh" },
  { pincode: "175131", city: "Manali", state: "Himachal Pradesh" },
  { pincode: "248001", city: "Dehradun", state: "Uttarakhand" },
  { pincode: "263001", city: "Nainital", state: "Uttarakhand" },
  { pincode: "244001", city: "Haridwar", state: "Uttarakhand" },
  { pincode: "144001", city: "Jalandhar", state: "Punjab" },
  { pincode: "143001", city: "Amritsar", state: "Punjab" },
  { pincode: "141001", city: "Ludhiana", state: "Punjab" },
  { pincode: "147001", city: "Patiala", state: "Punjab" },

  // South India
  { pincode: "560001", city: "Bangalore", state: "Karnataka" },
  { pincode: "560037", city: "Electronic City", state: "Karnataka" },
  { pincode: "575001", city: "Mangalore", state: "Karnataka" },
  { pincode: "580001", city: "Hubli", state: "Karnataka" },
  { pincode: "590001", city: "Belgaum", state: "Karnataka" },
  { pincode: "583101", city: "Hampi", state: "Karnataka" },
  { pincode: "600001", city: "Chennai", state: "Tamil Nadu" },
  { pincode: "625001", city: "Madurai", state: "Tamil Nadu" },
  { pincode: "641001", city: "Coimbatore", state: "Tamil Nadu" },
  { pincode: "620001", city: "Trichy", state: "Tamil Nadu" },
  { pincode: "635001", city: "Hosur", state: "Tamil Nadu" },
  { pincode: "500001", city: "Hyderabad", state: "Telangana" },
  { pincode: "500032", city: "Hi-Tech City", state: "Telangana" },
  { pincode: "506001", city: "Warangal", state: "Telangana" },
  { pincode: "695001", city: "Thiruvananthapuram", state: "Kerala" },
  { pincode: "682001", city: "Kochi", state: "Kerala" },
  { pincode: "673001", city: "Kozhikode", state: "Kerala" },
  { pincode: "686001", city: "Kottayam", state: "Kerala" },
  { pincode: "520001", city: "Vijayawada", state: "Andhra Pradesh" },
  { pincode: "530001", city: "Visakhapatnam", state: "Andhra Pradesh" },
  { pincode: "522001", city: "Guntur", state: "Andhra Pradesh" },
  { pincode: "515001", city: "Anantapur", state: "Andhra Pradesh" },

  // West India
  { pincode: "400001", city: "Mumbai", state: "Maharashtra" },
  { pincode: "400061", city: "Powai", state: "Maharashtra" },
  { pincode: "411001", city: "Pune", state: "Maharashtra" },
  { pincode: "440001", city: "Nagpur", state: "Maharashtra" },
  { pincode: "431001", city: "Aurangabad", state: "Maharashtra" },
  { pincode: "416001", city: "Kolhapur", state: "Maharashtra" },
  { pincode: "380001", city: "Ahmedabad", state: "Gujarat" },
  { pincode: "395001", city: "Surat", state: "Gujarat" },
  { pincode: "390001", city: "Vadodara", state: "Gujarat" },
  { pincode: "364001", city: "Bhavnagar", state: "Gujarat" },
  { pincode: "370001", city: "Rajkot", state: "Gujarat" },
  { pincode: "403001", city: "Panaji", state: "Goa" },
  { pincode: "403004", city: "Margao", state: "Goa" },
  { pincode: "403101", city: "Calangute", state: "Goa" },

  // East India
  { pincode: "700001", city: "Kolkata", state: "West Bengal" },
  { pincode: "711101", city: "Howrah", state: "West Bengal" },
  { pincode: "734001", city: "Siliguri", state: "West Bengal" },
  { pincode: "713301", city: "Durgapur", state: "West Bengal" },
  { pincode: "800001", city: "Patna", state: "Bihar" },
  { pincode: "842001", city: "Muzaffarpur", state: "Bihar" },
  { pincode: "846001", city: "Bhagalpur", state: "Bihar" },
  { pincode: "751001", city: "Bhubaneswar", state: "Odisha" },
  { pincode: "753001", city: "Cuttack", state: "Odisha" },
  { pincode: "760001", city: "Puri", state: "Odisha" },
  { pincode: "781001", city: "Guwahati", state: "Assam" },
  { pincode: "785001", city: "Dibrugarh", state: "Assam" },
  { pincode: "788001", city: "Silchar", state: "Assam" },
  { pincode: "795001", city: "Imphal", state: "Manipur" },
  { pincode: "797001", city: "Kohima", state: "Nagaland" },
  { pincode: "791001", city: "Itanagar", state: "Arunachal Pradesh" },
  { pincode: "793001", city: "Shillong", state: "Meghalaya" },
  { pincode: "796001", city: "Aizawl", state: "Mizoram" },
  { pincode: "799001", city: "Agartala", state: "Tripura" },
  { pincode: "737101", city: "Gangtok", state: "Sikkim" },

  // Central India
  { pincode: "462001", city: "Bhopal", state: "Madhya Pradesh" },
  { pincode: "482001", city: "Jabalpur", state: "Madhya Pradesh" },
  { pincode: "452001", city: "Indore", state: "Madhya Pradesh" },
  { pincode: "474001", city: "Gwalior", state: "Madhya Pradesh" },
  { pincode: "485001", city: "Satna", state: "Madhya Pradesh" },
  { pincode: "492001", city: "Raipur", state: "Chhattisgarh" },
  { pincode: "495001", city: "Bilaspur", state: "Chhattisgarh" },
  { pincode: "496001", city: "Jagdalpur", state: "Chhattisgarh" },

  // Union Territories
  { pincode: "682551", city: "Kavaratti", state: "Lakshadweep" },
  { pincode: "744101", city: "Port Blair", state: "Andaman and Nicobar Islands" },
  { pincode: "396193", city: "Silvassa", state: "Dadra and Nagar Haveli" },
  { pincode: "396210", city: "Daman", state: "Daman and Diu" },
  { pincode: "605001", city: "Pondicherry", state: "Puducherry" }
];